language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH

script:
  - cargo build
  - cargo build --no-default-features --features 'dummy'
  - cargo test --no-default-features --features 'dummy'
  # Not implemented yet
  # - ([ $TRAVIS_RUST_VERSION != nightly ] || cargo build --no-default-features --features 'proc-macro')
  - ([ $TRAVIS_RUST_VERSION != nightly ] || cargo build --features 'i128')

notifications:
  email:
    on_success: never
